// packages/create-shiftapi/templates/next/apps/web/app/page.tsx
"use client";

import { useState } from "react";
import { api } from "./api";

export default function Home() {
  const [message, setMessage] = useState("");
  const health = api.useQuery("get", "/health");
  const echo = api.useMutation("post", "/echo");

  if (health.isLoading) return <p>Loading...</p>;
  if (health.error) return <p>Health check failed: {health.error.message}</p>;

  return (
    <main style={{ fontFamily: "system-ui", padding: "2rem" }}>
      <h1>{"{{name}}"}</h1>
      <p style={{ color: "green" }}>
        Health check: OK ({JSON.stringify(health.data)})
      </p>
      <hr />
      <h2>Echo</h2>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          const trimmed = message.trim();
          if (!trimmed) return;
          echo.mutate(
            { body: { message: trimmed } },
            { onSuccess: () => setMessage("") },
          );
        }}
      >
        <input
          type="text"
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          placeholder="Enter a message"
        />
        <button type="submit" disabled={echo.isPending}>
          Send
        </button>
      </form>
      {echo.isPending && <p>Loading...</p>}
      {echo.error && <p>Error: {echo.error.message}</p>}
      {echo.data && <pre>Echo: {echo.data.message}</pre>}
    </main>
  );
}

// packages/create-shiftapi/templates/svelte/apps/web/src/App.svelte
<script lang="ts">
  import { client } from "@shiftapi/client";

  let output = $state("");

  $effect(() => {
    client.GET("/health").then(({ error }) => {
      if (error) {
        output = `Health check failed: ${error.message}`;
      } else {
        output = "Health check passed. Try sending a message.";
      }
    });
  });

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    const formData = new FormData(e.currentTarget as HTMLFormElement);
    const message = (formData.get("message") as string).trim();
    if (!message) return;
    output = "Loading...";
    const { data, error } = await client.POST("/echo", { body: { message } });
    if (error) {
      output = `Error: ${error.message}`;
    } else {
      output = `Echo: ${data.message}`;
    }
  }
</script>

<div>
  <h1>{{name}}</h1>
  <form onsubmit={handleSubmit}>
    <input type="text" name="message" placeholder="Enter a message" />
    <button type="submit">Send</button>
  </form>
  <pre>{output}</pre>
</div>
