// packages/create-shiftapi/templates/react/apps/web/src/App.tsx
import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { client } from "@shiftapi/client";

export default function App() {
  const [output, setOutput] = useState("");

  useEffect(() => {
    client.GET("/health").then(({ error }) => {
      if (error) {
        setOutput(`Health check failed: ${error.message}`);
      } else {
        setOutput("Health check passed. Try sending a message.");
      }
    });
  }, []);

  async function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const message = (formData.get("message") as string).trim();
    if (!message) return;
    setOutput("Loading...");
    const { data, error } = await client.POST("/echo", { body: { message } });
    if (error) {
      setOutput(`Error: ${error.message}`);
    } else {
      setOutput(`Echo: ${data.message}`);
    }
  }

  return (
    <div>
      <h1>{{name}}</h1>
      <form onSubmit={handleSubmit}>
        <input type="text" name="message" placeholder="Enter a message" />
        <button type="submit">Send</button>
      </form>
      <pre>{output}</pre>
    </div>
  );
}

// packages/create-shiftapi/templates/svelte/apps/web/src/App.svelte
<script lang="ts">
  import { client } from "@shiftapi/client";

  let output = $state("");

  $effect(() => {
    client.GET("/health").then(({ error }) => {
      if (error) {
        output = `Health check failed: ${error.message}`;
      } else {
        output = "Health check passed. Try sending a message.";
      }
    });
  });

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    const formData = new FormData(e.currentTarget as HTMLFormElement);
    const message = (formData.get("message") as string).trim();
    if (!message) return;
    output = "Loading...";
    const { data, error } = await client.POST("/echo", { body: { message } });
    if (error) {
      output = `Error: ${error.message}`;
    } else {
      output = `Echo: ${data.message}`;
    }
  }
</script>

<div>
  <h1>{{name}}</h1>
  <form onsubmit={handleSubmit}>
    <input type="text" name="message" placeholder="Enter a message" />
    <button type="submit">Send</button>
  </form>
  <pre>{output}</pre>
</div>
